# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package.json pnpm-lock.yaml ./

# Use pnpm if available, otherwise fallback to npm
RUN npm install -g pnpm && pnpm install --frozen-lockfile --ignore-scripts

# Copy source files
COPY tsconfig.json ./
COPY src ./src

# Build the project
RUN pnpm run build

# Expose port (if applicable), default 3000
EXPOSE 3000

# Run the MCP server
CMD ["node", "build/index.js"]
